export const typeColors = {
    normal: "secondary",
    fire: "danger",
    water: "primary",
    electric: "warning",
    grass: "success",
    ice: "info",
    fighting: "danger",
    poison: "secondary",
    ground: "warning",
    flying: "info",
    psychic: "info",
    bug: "success",
    rock: "dark",
    ghost: "dark",
    dragon: "danger",
    dark: "dark",
    steel: "secondary",
    fairy: "info",
};